# Generated by Django 4.2.4 on 2023-10-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(related_name='users', through='users.UserRole', to='users.role'),
        ),
    ]
